### ISSUE TITLE
Getting error "Default resolvers at the root level are not supported" following the custom subscriptions guide

### ISSUE THREAD

**Issue by parris** [graphile/operation-hooks#11]
Hello! I'm following the guide for custom subscriptions here: https://www.graphile.org/postgraphile/subscriptions/

Which results in the following error for me on server start: `Error: Default resolver found for field Subscription.communityFeedItemCommentAdded; default resolvers at the root level are not supported by operation-hooks…`

Here is my plugin:

```
const topicFromArgs = (args) => {
  return `graphql:communityFeedItemComments:${args.communityFeedItemId}`;
};

makeExtendSchemaPlugin(
  ({ pgSql: sql }) => ({
    typeDefs: gql`
      type CommunityFeedItemCommentSubscriptionPayload {
        communityFeedItemComment: CommunityFeedItemComment
        event: String
      }
      extend type Subscription {
        communityFeedItemCommentAdded(communityFeedItemId: Int!): CommunityFeedItemCommentSubscriptionPayload @pgSubscription(topic: ${embed(topicFromArgs)})
      }
    `,
    resolvers: {
      CommunityFeedItemCommentSubscriptionPayload: {
        async communityFeedItemComment(...args) {
          return require('./resolver').default(sql, ...args); // used to hot reload code in dev
        },
      },
    },
  }),
)
```

```
// resolver.js
export default async (
  sql,
  event,
  _args,
  _context,
  { graphile: { selectGraphQLResultFromTable } },
) => {
  const rows = await selectGraphQLResultFromTable(
    sql.fragment`public.community_feed_item_comment`,
    (tableAlias, sqlBuilder) => {
      sqlBuilder.where(
        sql.fragment`${tableAlias}.id = ${sql.value(event.subject)}`,
      );
    },
  );
  return {
    communityFeedItemComment: rows[0],
    event,
  };
};
```

If I explicitly create a resolver for communityFeedItemCommentAdded, then *I think* `selectGraphQLResultFromTable` doesn't look ahead nor does it collect the fields. Thus leading back to the above error.

Any ideas about how to resolve? Thanks!

**Comment by parris** [comment]
I think I got it working, this is either a workaround or it should be in the documentation:

So I added a very simply resolver for the subscription:

```
    resolvers: {
      CommunityFeedItemCommentSubscriptionPayload: {
        async communityFeedItemComment(...args) {
          return require('./resolver').default(sql, ...args); // eslint-disable-line global-require
        },
      },
      Subscription: {
        communityFeedItemCommentAdded: (event) => ({ event }),
      },
    },
```

The event needs to get passed through so we have access the to the `subject` in the Payload resolver.

After that, everything seems to connect and work properly. Look aheads work, the query builder effectively does the look ahead and the resulting sql executed/produced seems accurate (based on looking at the query logs and debugging.

**Comment by benjie** [comment]
@parris Can you confirm the order in which you're loading the pubsub and operationhooks plugins? I think you have to load pubsub first, then operation hooks.

**Comment by parris** [comment]
@benjie ahh - maybe that's it `const pluginHook = makePluginHook([OperationHooks, PgPubsub, GraphilePro]);`

**Comment by parris** [comment]
I was following the order found here https://www.graphile.org/postgraphile/plugins/ if I recall correctly. Perhaps the doc should get modified?

**Comment by benjie** [comment]
@parris Can you confirm if this solved the issue? If so, a mod to the doc would be welcome :+1:

**Comment by parris** [comment]
@benjie - I had a chance to look into this. Changing the order of the hooks does not impact this. In a fresh project (not using any other libraries between postgraphile and the codebase), and _using mutations instead of subscriptions_ I've found the same thing to occur.

Example:

```
makeExtendSchemaPlugin(({ pgSql: sql }) => ({
    typeDefs: gql`
      type AuthenticationDetails {
        person: Person!
        jwtToken: String!
      }
      type RegisterPayload {
        authenticationDetails: AuthenticationDetails!
      }
    `,
     resolvers: {
      RegisterPayload: {
        async authenticationDetails(...args) {
          return resolver.registerPerson(sql, ...args);
        },
      },
    },
  },
} as ExtensionDefinition)),
```

This will throw `Error: Default resolver found for field Mutation.registerPerson; default resolvers at the root level are not supported by operation-hooks`

However, even doing something as simple as the following resolves the issue.
```
Mutation: {
   registerPerson: () => ({}),
}
```

**Comment by benjie** [comment]
My guess is that things are running out of phase - operation hooks is trying to mod the resolver before it’s added by makeExtendSchemaPlugin. I’m not sure what we can do about this in v4.

**Comment by benjie** [comment]
Fixed in v1 :+1:
