### ISSUE TITLE
Question about the format of callback's 'input' argument

### ISSUE THREAD

**Issue by balasan** [graphile/operation-hooks#14]
I'm using the operation hooks plugin and I'm confused about the format of the `input` field of the callback. 
This is what it looks like for my query:
```
{    
    data: [
      { '@nodes': { __identifiers: [1], username: 'alice' } },
      { '@nodes': { __identifiers: [2], username: 'bob' } }
    ],
    startCursor: null,
    endCursor: null
}
```
And this is the result of the same query that I get on the frontend:
```
{
    users: {
      nodes: [
        { username: 'alice', __typename: 'User' },
        { username: 'bob', __typename: 'User' }
      ],
      __typename: 'UsersConnection'
    }
}
```
I'm trying to get the `input` in the callback into the latter format, but have no idea where to start. What is the best way to go about this?

**Comment by benjie** [comment]
The data from the first code block is generated by the lookahead system/etc. It can change in patch versions and is heavily influenced by user input in the query itself. You are not expected to deal with anything that contains an `@` symbol; these implementation details are internal.

This question is not one you should be asking; could you share what you're trying to achieve so that I can perhaps guide you down a better path?

**Comment by balasan** [comment]
Thanks @benjie 
I'm working on a micro-payment system for graphql queries. I'm using the `after` hook to request a payment from the client based on the size of the response payload. The request is throttled until payment is received. I have all the logic working well except:
 - I need to be able to generate a hash of the payload that the client can later match against the payments they made (an alternative solution might be attaching the hash of the `input` to the payload)
 - I also need the payload to be in its final form when pricing the data to enable the client to later verify that they were charged the right amount

Would really appreciate your advice on how I can accomplish this.

**Comment by benjie** [comment]
As discussed in chat, this needs to be done outside of GraphQL after GraphQL has resolved. One option is to use a server plugin for this, it should work for queries and mutations but we don’t have hooks for post-processing subscription bodies currently.
