### ISSUE TITLE
Logic error: operation hook returned 'undefined' with Byid queries

### ISSUE THREAD

**Issue by dgkm** [graphile/operation-hooks#4]
We are getting an error "Logic error: operation hook returned 'undefined'." when no record found with any "*ById" query on any table. 

This error seems to be coming from "graphql/oprational-hooks".

_**Environment to reproduce the issue:**_
- run the postgraphile with the following hooks:
     makePluginHook([OperationHooks, PgPubsub, subscriptionsLds]);
-  execute  *ById query on any table passing non existing record *id to reproduce the error

>**Example to reproduce:**
>> **Table:**
>>>`CREATE TABLE account (
     "id" serial primary key,
    "firstName" text,
    "lastName" text,
    "dateOfBirth" date,
    "createdAt" timestamptz not null default now(),
    "updatedAt" timestamptz not null default now()
)        
`
>

>> **Sample Request:**

>>> Note: Any non existing record id, example id = 10, a non existing record.

>>> `{
  accountById(id: 10) {
    id
  }
}
`

>>**Sample Response:**
>>>`{
  "errors": [
    {
      "message": "Logic error: operation hook returned 'undefined'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "accountById"
      ],
      "extensions": {
        "messages": []
      }
    }
  ],
  "data": {
    "accountById": null
  }
}`

@benjie, Please let me know if you need any further information to reproduce the issue.

**Comment by nickreese** [comment]
Hitting this issue as well.

**Comment by benjie** [comment]
This is fixed in `@graphile/operation-hooks@0.2.4` :+1:
