### ISSUE TITLE
Access RAISE NOTICE details from GraphQL client

### ISSUE THREAD

**Issue by kzlar** [graphile/operation-hooks#40]
### Feature description

I've been using https://github.com/graphile/operation-hooks/pull/16 to add out of band messages to my GraphQL mutations and it has been a blast! In my usage I employ `detail = json_build_object(...)` to add auxiliary data to my messages and I am able to access them in my operation hooks on the server.

However, while I'm able to access the `messages` part on my GraphQL client, I'm unable to access the `detail` part since it's not a part of `OperationMessageInterface` in the GraphQL schema.

### Motivating example

Really any time you'd use `detail` as part of your notice and want to add auxiliary data. e.g. expanding on the minimal example in the README:

`RAISE NOTICE 'Your credits are running low.' USING ERRCODE = 'OPMSG', detail = json_build_object('remaining_credits',5);`

### Breaking changes

This is only expanding the GraphQL schema, don't believe anything is breaking.

### Supporting development

- [ ] am interested in building this feature myself
(would tick this if I thought I was capable of doing it myself 😅 )
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by kzlar** [comment]
Ended up taking a stab at a PR: https://github.com/graphile/operation-hooks/pull/41 
As I mentioned in discord, no rush on this, when you're back and have a moment to review, please let me know how this looks to you :)

**Comment by benjie** [comment]
I think this is already possible using simple schema extensions; see: https://github.com/graphile/operation-hooks/pull/41#pullrequestreview-1801874775
